ID3v2: Create more concrete types for `FrameValue` variants
Serial-ATA/lofty-rs pull request #184
Opened 2023-04-12 00:24 UTC by Serial-ATA

This makes working with `FrameValue` nicer, as there are no longer struct variants and reused types.

`FrameValue` before:

```rs
pub enum FrameValue {
	Comment(LanguageFrame),
	UnSyncText(LanguageFrame),
	Text {
		/// The encoding of the text
		encoding: TextEncoding,
		/// The text itself
		value: String,
	},
	UserText(EncodedTextFrame),
	URL(String),
	UserURL(EncodedTextFrame),
	Picture {
		/// The encoding of the description
		encoding: TextEncoding,
		/// The picture itself
		picture: Picture,
	},
	Popularimeter(Popularimeter),
	Binary(Vec<u8>),
	UniqueFileIdentifier(UniqueFileIdentifierFrame),
}
```

After:

```rs
pub enum FrameValue {
	Comment(CommentFrame),
	UnSyncText(UnsynchronizedTextFrame),
	Text(TextInformationFrame),
	UserText(ExtendedTextFrame),
	URL(UrlLinkFrame),
	UserURL(ExtendedUrlFrame),
	Picture(AttachedPictureFrame),
	Popularimeter(Popularimeter),
	Binary(Vec<u8>),
	UniqueFileIdentifier(UniqueFileIdentifierFrame),
}
```

It also allowed for all of the parsing logic to be moved to the respective structs, making things cleaner.

2023-04-12 08:13 UTC, uklotzde commented
Having distinct types for the variants is more flexible and avoids redundant and boilerplate type conversion.

2023-04-12 08:16 UTC, uklotzde requested changes
I would prefer to follow consistent naming rules for `FrameValue::UnSyncText` like for all other frame value types, i.e. `FrameValue::UnsynchronizedText(UnsynchronizedTextFrame)`.

2023-04-12 08:23 UTC, uklotzde commented
I would also propose to rename the `URL` variants according to the Rust API naming conventions:

- `Url(UrlLinkFrame)`
- `UserUrl(ExtendedUrlFrame)`

This is an opportunity for doing it.

2023-04-12 19:53 UTC, uklotzde commented on src/id3/v2/write/frame.rs
> +				FrameValue::UnsynchronizedText(_) => "UnSyncText",
These strings need to be updated, too.

2023-04-13 02:08 UTC, Serial-ATA commented on src/id3/v2/write/frame.rs
> +				FrameValue::UnsynchronizedText(_) => "UnSyncText",
Good catch :smile:

2023-04-13 08:14 UTC, uklotzde approved these changes

2023-04-14 06:44 UTC, merged