Rust v1.70: Replace once_cell with std::sync::OnceLock
Serial-ATA/lofty-rs pull request #303
Opened 2023-12-21 11:44 UTC by uklotzde

2023-12-21 22:12 UTC, Serial-ATA commented
Honestly, I'd rather wait for `LazyLock` to finally get stabilized (probably going to be at least another year from now, given how slowly things move in std). It's a lot simpler to work with, and lofty has few dependencies anyway.

Unless, of course, there is some advantage to using `OnceLock` that I don't know about?

2023-12-21 22:34 UTC, uklotzde commented
> Unless, of course, there is some advantage to using `OnceLock` that I don't know about?

Just one less dependency, no other advantages.

I wasn't aware of the plans for the `LazyLock` wrapper. Sounds like it only adds a more convenient API that avoids some boilerplate for simple cases.

2023-12-21 22:44 UTC, uklotzde commented
Using a local, static instance inside the functions doesn't add much boilerplate and keeps the namespace clean.

The migration to `LazyLock`would be straightforward when it becomes available. Then you you also need to bump the MSRV again.

2023-12-22 01:17 UTC, Serial-ATA requested changes
Sure, this seems alright. I just don't want to specify an MSRV right now.

2023-12-22 01:17 UTC, Serial-ATA commented on Cargo.toml
> +rust        = "1.70.0"
```suggestion
```
I'd rather not make any guarantees about the MSRV yet. I always just use the latest stable, so this is something extra I'd have to remember to bump on each release.

2023-12-22 01:44 UTC, Serial-ATA commented
Thanks!

2023-12-22 01:44 UTC, merged